source "https://rubygems.org"

gem "fastlane", "~> 2.225"
gem "cocoapods", "~> 1.15"
gem "xcpretty", "~> 0.3"

plugins_path = File.join(File.dirname(__FILE__), "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
