workspace("MaltaCalculator.xcworkspace")
scheme("MaltaCalculator")

devices([
  "iPhone 16 Pro Max",
  "iPad Pro (13-inch) (M4)"
])

languages(["en-US"])

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(false)
