import Foundation

/// Aggregated tax configuration for Malta (2020–2026), used by all calculator motors.
///
/// Loaded from a bundled JSON via ``TaxConfigStore``. The JSON is generated by
/// `scripts/export-tax-config.ts` from the web app's canonical TypeScript config.
public struct MaltaTaxConfig: Sendable {

    /// Schema version of the JSON config (e.g. "2026.1").
    public let version: String

    /// ISO-8601 timestamp when the JSON was generated.
    public let generatedAt: String

    /// All year configurations keyed by year.
    public let years: [Int: YearConfig]

    /// Creates a new config from parsed components.
    public init(version: String, generatedAt: String, years: [Int: YearConfig]) {
        self.version = version
        self.generatedAt = generatedAt
        self.years = years
    }

    // MARK: - Nested Types

    /// Per-year configuration data.
    public struct YearConfig: Sendable {
        /// The tax year.
        public let year: Int
        /// Tax brackets keyed by rate type.
        public let brackets: [TaxRateType: [TaxBracket]]
        /// Social Security Contribution rates.
        public let ssc: SSCRates
        /// COLA (Cost of Living Adjustment) quarterly payments. Zero amounts when no COLA for that year.
        public let cola: COLAConfig
    }

    /// A single tax bracket within a rate type.
    public struct TaxBracket: Sendable, Codable, Equatable {
        /// Lower bound of the bracket (inclusive).
        public let min: Money
        /// Upper bound of the bracket (inclusive). `Decimal.greatestFiniteMagnitude` for the top bracket.
        public let max: Money
        /// Tax rate as a decimal (e.g. 0.15 for 15%).
        public let rate: Decimal
        /// Deduction amount.
        public let deduction: Money

        /// Creates a new tax bracket.
        public init(min: Money, max: Money, rate: Decimal, deduction: Money) {
            self.min = min
            self.max = max
            self.rate = rate
            self.deduction = deduction
        }

        /// Whether the given income falls within this bracket.
        public func contains(_ income: Money) -> Bool {
            income >= min && income <= max
        }
    }

    /// SSC rates for a given year.
    public struct SSCRates: Sendable, Codable, Equatable {
        /// Weekly rate for category A (pensioners).
        public let categoryA: Money
        /// Weekly rate for category B (part-time/low wage).
        public let categoryB: Money
        /// Weekly rate for category C, born before 1962.
        public let categoryCOld: Money
        /// Weekly rate for category C, born 1962 or later.
        public let categoryCNew: Money
        /// Weekly rate for category D, born before 1962.
        public let categoryDOld: Money
        /// Weekly rate for category D, born 1962 or later.
        public let categoryDNew: Money
        /// Weekly SSC base cap for born-before-1962.
        public let weeklyCapOld: Money
        /// Weekly SSC base cap for born-1962-or-later.
        public let weeklyCapNew: Money
        /// National minimum weekly wage.
        public let minimumWage: Money
    }

    /// COLA (Cost of Living Adjustment) quarterly payments.
    public struct COLAConfig: Sendable, Equatable {
        /// March (Q1) payment.
        public let march: Money
        /// June (Q2) payment.
        public let june: Money
        /// September (Q3) payment.
        public let september: Money
        /// December (Q4) payment.
        public let december: Money

        /// Returns the COLA amount for a given month, or zero if not a COLA month.
        public func amount(for month: Month) -> Money {
            switch month {
            case .march: march
            case .june: june
            case .september: september
            case .december: december
            default: 0
            }
        }
    }
}

// MARK: - Helper Accessors

public extension MaltaTaxConfig {
    /// Available years sorted ascending.
    var availableYears: [Int] {
        years.keys.sorted()
    }

    /// Returns tax brackets for a given year and rate type, with fallback to base type then single.
    func brackets(for year: Int, type: TaxRateType) -> [TaxBracket] {
        guard let yearConfig = years[year] else { return [] }
        if let exact = yearConfig.brackets[type] { return exact }
        // Fallback: married_1child → married, parent_2plus → parent
        let baseKey = type.rawValue
            .replacingOccurrences(of: "_1child", with: "")
            .replacingOccurrences(of: "_2plus", with: "")
        if let base = TaxRateType(rawValue: baseKey),
           let brackets = yearConfig.brackets[base] {
            return brackets
        }
        return yearConfig.brackets[.single] ?? []
    }

    /// Returns SSC rates for a given year, or nil if the year is not configured.
    func ssc(for year: Int) -> SSCRates? {
        years[year]?.ssc
    }

    /// Returns the COLA amount for a given year and month.
    func cola(for year: Int, month: Month) -> Money {
        years[year]?.cola.amount(for: month) ?? 0
    }

    /// Whether child count affects tax brackets for the given year (2026+).
    static func isChildCountEffective(year: Int) -> Bool {
        year >= 2026
    }
}
